# ----------------------------
# Makefile Options
# ----------------------------

NAME = GJK
ICON = icon.png
DESCRIPTION = "Test GJK Collision Detection"
COMPRESSED = NO

CFLAGS = -Wall -Wextra -Oz -DTI84PCE
CXXFLAGS = -Wall -Wextra -Oz -DTI84PCE

# ----------------------------

include $(shell cedev-config --makefile)
